### ISSUE TITLE
Pull Request issue?

### ISSUE THREAD

**Issue by I-Cat** [AlwinEsch/kodi#40]
### Describe the bug
Here is a clear and concise description of what the problem is:

I made a pull request and it didn't set up properly with the assinees and lables

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by I-Cat** [comment]
Opened

**Comment by I-Cat** [comment]
Opened

**Comment by AlwinEsch** [comment]
As you seem to never learn how exact changes are done becomes you blocked.

Changes are usually welcome, but since you never describe what and why and where it is where it is impossible to explain why.

So I had ignored them so far, as information was already coming from some in the team and requests from others can also be seen how structured.
